const COOKIE="shop_session";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CATEGORIES=new Set(["잡화","뷰티","신발","식품"]);
class ApiError extends Error{constructor(status,code,message,headers){super(message);this.status=status;this.code=code;this.headers=headers;}}
const json=(d,s=200,e)=>{const h=new Headers(e);h.set("Content-Type","application/json; charset=utf-8");h.set("Cache-Control","no-store");h.set("X-Content-Type-Options","nosniff");return new Response(JSON.stringify(d),{status:s,headers:h});};
const fail=e=>e instanceof ApiError?json({error:{code:e.code,message:e.message}},e.status,e.headers):json({error:{code:"internal_error",message:"요청을 처리하지 못했습니다."}},500);
function session(r){const c=r.headers.get("Cookie")||"";for(const p of c.split(";")){const i=p.indexOf("=");if(i>=0&&p.slice(0,i).trim()===COOKIE&&UUID.test(p.slice(i+1).trim()))return{id:p.slice(i+1).trim().toLowerCase(),new:false};}return{id:crypto.randomUUID(),new:true};}
function cookie(id,u){return `${COOKIE}=${id}; Path=/; HttpOnly; SameSite=Lax${u.protocol==="https:"?"; Secure":""}`;}
async function body(r){if(!(r.headers.get("Content-Type")||"").toLowerCase().startsWith("application/json"))throw new ApiError(415,"unsupported_media_type","JSON 형식으로 요청해 주세요.");const t=await r.text();if(t.length>4096)throw new ApiError(413,"body_too_large","요청 내용이 너무 큽니다.");try{const v=JSON.parse(t);if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v;}catch{throw new ApiError(400,"invalid_json","올바른 JSON 요청이 아닙니다.");}}
function qty(v){if(!Number.isInteger(v)||v<1||v>99)throw new ApiError(400,"invalid_quantity","수량은 1 이상 99 이하의 정수여야 합니다.");return v;}
function pid(v){if(!/^[1-9]\d*$/.test(v)||!Number.isSafeInteger(Number(v)))throw new ApiError(404,"product_not_found","상품을 찾을 수 없습니다.");return Number(v);}
async function products(env,u){const c=u.searchParams.get("category");if(c&&!CATEGORIES.has(c))throw new ApiError(400,"invalid_category","존재하지 않는 분류입니다.");const q="SELECT id,name,price,description,category,image_url AS imageUrl FROM products"+(c?" WHERE category=?":"")+" ORDER BY id";const r=await env.DB.prepare(q).bind(...(c?[c]:[])).all();return json({products:r.results||[]});}
async function product(env,id){const p=await env.DB.prepare("SELECT id,name,price,description,category,image_url AS imageUrl FROM products WHERE id=?").bind(id).first();if(!p)throw new ApiError(404,"product_not_found","상품을 찾을 수 없습니다.");return json({product:p});}
async function cartData(env,s){const r=await env.DB.prepare("SELECT ci.id,p.id AS productId,p.name,p.price,p.description,p.category,p.image_url AS imageUrl,ci.qty,ci.qty*p.price AS lineTotal FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.session_id=? ORDER BY ci.id").bind(s).all();const items=r.results||[];return{items,total:items.reduce((a,x)=>a+Number(x.lineTotal),0)};}
async function cart(r,env,s){if(r.method==="GET")return json(await cartData(env,s));if(r.method!=="POST")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"GET, POST"});const b=await body(r);if(!Number.isSafeInteger(b.productId)||b.productId<1)throw new ApiError(400,"invalid_input","상품 번호가 올바르지 않습니다.");const n=qty(b.qty);if(!await env.DB.prepare("SELECT id FROM products WHERE id=?").bind(b.productId).first())throw new ApiError(404,"product_not_found","상품을 찾을 수 없습니다.");const u=await env.DB.prepare("INSERT INTO cart_items(session_id,product_id,qty) VALUES(?,?,?) ON CONFLICT(session_id,product_id) DO UPDATE SET qty=cart_items.qty+excluded.qty WHERE cart_items.qty+excluded.qty<=99 RETURNING qty").bind(s,b.productId,n).first();if(!u)throw new ApiError(409,"quantity_limit_exceeded","같은 상품은 장바구니에 99개까지 담을 수 있습니다.");return json(await cartData(env,s));}
async function cartItem(r,env,s,id){if(r.method==="DELETE"){const x=await env.DB.prepare("DELETE FROM cart_items WHERE session_id=? AND product_id=?").bind(s,id).run();if(!x.meta?.changes)throw new ApiError(404,"cart_item_not_found","장바구니에서 상품을 찾을 수 없습니다.");return json(await cartData(env,s));}if(r.method!=="PATCH")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"PATCH, DELETE"});const n=qty((await body(r)).qty);if(!await env.DB.prepare("UPDATE cart_items SET qty=? WHERE session_id=? AND product_id=? RETURNING id").bind(n,s,id).first())throw new ApiError(404,"cart_item_not_found","장바구니에서 상품을 찾을 수 없습니다.");return json(await cartData(env,s));}
async function orderGet(env,s,id){if(!UUID.test(id))throw new ApiError(404,"order_not_found","주문을 찾을 수 없습니다.");const o=await env.DB.prepare("SELECT id,total,status,created_at AS createdAt FROM orders WHERE id=? AND session_id=?").bind(id.toLowerCase(),s).first();if(!o)throw new ApiError(404,"order_not_found","주문을 찾을 수 없습니다.");const r=await env.DB.prepare("SELECT oi.product_id AS productId,p.name,p.description,oi.price,p.image_url AS imageUrl,oi.qty,oi.qty*oi.price AS lineTotal FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE oi.order_id=? ORDER BY oi.id").bind(id.toLowerCase()).all();return json({order:{...o,items:r.results||[]}});}
async function orderCreate(env,s){const id=crypto.randomUUID(),at=new Date().toISOString();const rs=await env.DB.batch([env.DB.prepare("INSERT INTO orders(id,session_id,total,status,created_at) SELECT ?,?,SUM(ci.qty*p.price),'pending',? FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.session_id=? HAVING COUNT(*)>0").bind(id,s,at,s),env.DB.prepare("INSERT INTO order_items(order_id,product_id,qty,price) SELECT ?,ci.product_id,ci.qty,p.price FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.session_id=? ORDER BY ci.id").bind(id,s),env.DB.prepare("DELETE FROM cart_items WHERE session_id=?").bind(s)]);if(!rs[0]?.meta?.changes)throw new ApiError(409,"cart_empty","장바구니가 비어 있어 주문할 수 없습니다.");const resp=await orderGet(env,s,id);return json(await resp.json(),201);}
async function api(r,e,u,s){const p=u.pathname.replace(/\/$/,"");if(p==="/api/products"){if(r.method!=="GET")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"GET"});return products(e,u);}let m=p.match(/^\/api\/products\/([^/]+)$/);if(m){if(r.method!=="GET")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"GET"});return product(e,pid(m[1]));}if(p==="/api/cart")return cart(r,e,s);m=p.match(/^\/api\/cart\/([^/]+)$/);if(m)return cartItem(r,e,s,pid(m[1]));if(p==="/api/orders"){if(r.method!=="POST")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"POST"});return orderCreate(e,s);}m=p.match(/^\/api\/orders\/([^/]+)$/);if(m){if(r.method!=="GET")throw new ApiError(405,"method_not_allowed","허용되지 않은 요청 방식입니다.",{Allow:"GET"});return orderGet(e,s,m[1]);}throw new ApiError(404,"api_not_found","API 경로를 찾을 수 없습니다.");}
export default{async fetch(r,e){const u=new URL(r.url);if(!u.pathname.startsWith("/api/"))return e.ASSETS?.fetch?e.ASSETS.fetch(r):new Response("Not Found",{status:404});const s=session(r);let out;try{out=await api(r,e,u,s.id);}catch(err){out=fail(err);}if(s.new)out.headers.append("Set-Cookie",cookie(s.id,u));return out;}};
